data_type: keypoints
n_clusters: 10
seq_len: 90
stride: 30

hidden_ndim: 32
latent_ndim: 32
nheads: 4
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 32
emb_nheads: 4
emb_nlayers: 3
emb_dropout: 0.1
add_position_patch: True
patch_size: [32, 24]
img_size: [256, 192]

lrc_x: 1
lrc_bbox: 1
lg: 1
lc: 1

epochs: 100
batch_size: 16
accumulate_grad_batches: 32
lr: 0.0001
num_workers: 16
