# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
# n_clusters: 5
temp_init: 1.0
temp_decay: 0.01
temp_min: 0.01
book_size: 64
hidden_ndim: 512
latent_ndim: 128
nheads: 16
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 128
emb_nheads: 1
emb_nlayers: 3
emb_dropout: 0.1
patch_size: [32, 24]

# optim VAE
lmd_lrc: 0.1
lr: 0.0001

# training
epochs: 100
batch_size: 32
accumulate_grad_batches: 1
num_workers: 16
