data_type: images
n_clusters: 10
seq_len: 90
stride: 30

hidden_ndim: 32
latent_ndim: 32
nheads: 4
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 32
emb_nheads: 4
emb_nlayers: 3
emb_dropout: 0.1
add_position_patch: True
patch_size: [16, 12]
img_size: [256, 192]

lrc_x: 1
lrc_bbox: 1
lg: 1
lc: 1

epochs: 200
batch_size: 1
accumulate_grad_batches: 128
lr: 0.0001
