# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
n_clusters: 10
hidden_ndim: 64
latent_ndim: 32
nheads: 4
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 64
emb_nheads: 4
emb_nlayers: 6
emb_dropout: 0.1
patch_size: [32, 24]

# optim
lrc_x_vis: 2
lrc_x_spc: 1
lg: 5
lc: 1
lr: 0.0001

# training
epochs: 100
batch_size: 1
accumulate_grad_batches: 128
num_workers: 8
