data_type: images
seq_len: 90
stride: 30

hidden_ndim: 128
latent_ndim: 64
nheads: 8
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 128
emb_nheads: 8
emb_nlayers: 3
emb_dropout: 0.1
add_position_patch: True
patch_size: [16, 12]
img_size: [256, 192]

epochs: 200
batch_size: 4
accumulate_grad_batches: 256
lr: 0.0001
