# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
n_clusters: 10
tau: 0.5
hidden_ndim: 128
latent_ndim: 16
nheads: 8
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 32
emb_nheads: 1
emb_nlayers: 3
emb_dropout: 0.1
patch_size: [32, 24]

# optim VAE
lrc_x_vis: 1
lrc_x_spc: 1
lg: 8
lc: 1
lr: 0.0001

# optim pz_y
lr_py: 0.01
lr_pz_y: 0.01
alpha: 2
batch_size_pz_y: 16
epochs_pz_y: 1
update_interval: 5

# training
epochs: 200
batch_size: 16
accumulate_grad_batches: 1
num_workers: 16
