# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
n_clusters: 10
tau: 0.1
hidden_ndim: 64
latent_ndim: 32
nheads: 8
nlayers: 6
dropout: 0.2
emb_hidden_ndim: 64
emb_nheads: 8
emb_nlayers: 6
emb_dropout: 0.2
patch_size: [32, 24]

# optim
lrc_x_vis: 1
lrc_x_spc: 1
lg: 1
lc: 1
lr: 0.0001

# training
epochs: 100
batch_size: 16
accumulate_grad_batches: 1
num_workers: 8
interval_kl_loss: 1
