# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
n_clusters: 10
tau: 0.5  # VAE gumbel softmax
hidden_ndim: 128
latent_ndim: 10
nheads: 8
nlayers: 6
dropout: 0.2
emb_hidden_ndim: 128
emb_nheads: 8
emb_nlayers: 6
emb_dropout: 0.2
patch_size: [32, 24]

# optim VAE
lrc_x_vis: 1
lrc_x_spc: 1
lg: 16
lc: 1
lr: 0.0001

# training
epochs: 100
batch_size: 256
accumulate_grad_batches: 1
num_workers: 10
