# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]

# model
n_clusters: 5
tau: 0.1
hidden_ndim: 1024
latent_ndim: 16
nheads: 16
nlayers: 3
dropout: 0.1
emb_hidden_ndim: 16
emb_nheads: 1
emb_nlayers: 3
emb_dropout: 0.1
patch_size: [32, 24]

# optim VAE
lrc_x_kps: 1
lrc_x_bbox: 1
lg: 1
lc: 1
lr: 0.0001

# optim pz_y
lr_pz_y: 0.0001
alpha: 1
update_prior_interval: 1

# training
epochs: 50
batch_size: 32
accumulate_grad_batches: 1
num_workers: 16
