# dataset
max_shard_count: 100
seq_len: 90
stride: 30
img_size: [256, 192]
mask_leg: False

# model
n_clusters: 5
temp_init: 1.0
temp_decay: 0.001
temp_min: 0.001
param_q_init: 2
book_size: 32
hidden_ndim: 1024
latent_ndim: 16
nheads: 1
nlayers: 3
dropout: 0.1

# optim
lmd_lrc: 1
lmd_klc: 1
lmd_kld: 1
lmd_c: 1

lr: 0.001
lr_lmd: 0.99

# training
epochs: 100
batch_size: 32
accumulate_grad_batches: 1
num_workers: 8
