n_clusters: 10
seq_len: 90
stride: 30
img_size: [256, 192]

hidden_ndim: 256
latent_ndim: 32
nheads: 8
nlayers: 6
dropout: 0.1
emb_hidden_ndim: 256
emb_nheads: 8
emb_nlayers: 3
emb_dropout: 0.1
patch_size: [32, 24]

lrc_x_vis: 1
lrc_x_spc: 1
lg: 10
lc: 1

epochs: 100
batch_size: 1
accumulate_grad_batches: 128
num_workers: 16
lr: 0.0001
